# Exported from Render on 2025-06-24T02:12:05Z
services:
- type: web
  name: TheRoadie
  runtime: python
  repo: https://github.com/moneyesh/TheRoadie
  plan: free
  envVars:
  - key: secrets.sh
    sync: false
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn server:app
  autoDeployTrigger: commit
version: "1"

 